### ISSUE TITLE
'content-type': 'application/x-www-form-urlencoded' needs to pass in params as urlencoded string

### ISSUE THREAD

**Issue by matthiasprieth** [infinitered/apisauce#111]
When I set
```
headers: {
    'content-type': 'application/x-www-form-urlencoded'
}
```
i need to pass in params as a string. Maybe we could support JSON to urlencoded string conversion if those headers are set or have a line of code in the docs. Cause I thought it was working automatically like in JQuery and I searched a while till I realized i was passing params in the wrong format.

**Comment by skellock** [comment]
Sure. That sounds reasonable.

**Comment by maoueh** [comment]
Instead of "manually" passing it as string, we imported [qs](https://www.npmjs.com/package/qs) (query string) in our project and use it to convert an object to a valid form encoded string:

```
import qs from 'qs';

...

executeAction() {
  const data = {
    command: 'run',
    user: '123',
  };

  // The `{ encode: true }` is already the default value, but we prefer to be explicit 
  return api.post("/path", qs.stringify(data, { encode: true }));
}
```

Just wanted to share if anyone else arrive here

**Comment by skellock** [comment]
@maoueh Sweet!  Thanks for solution.  👍 

I think it'd be nice to have this kinda thing baked into apisauce, however I won't be able to do that myself.

If anyone is feeling up to it, I'd welcome this kinda thing.
