### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by AlexHenkel** [infinitered/apisauce#114]
I'm trying to use this in my Polymer app, so I can't use the regular Node package, but when I try to import this as `<script src="../../../node_modules/apisauce/dist/apisauce.js"></script>` it throws me the following error on browser:

```
Uncaught ReferenceError: exports is not defined
    at apisauce.js:1
```

Any thoughts on making this compatible with the browser?

**Comment by skellock** [comment]
Can you try version 0.13.0? In 0.14.0 I switched over to typescript and I think I might be missing something from my build chain.  Definitely want to supports browsers.

**Comment by AlexHenkel** [comment]
I've tried with almost all versions, but it seems that all of them depend on `Object.defineProperty(exports,"__esModule",{value:!0})` which is not supported by any browser

**Comment by skellock** [comment]
Ah.  I think that's because usually people use this with React, so it has another pass thru the babel ecosystem.

Lemme take a closer look at a vanilla browser build as well.

Thanks for filing this issue.

**Comment by skellock** [comment]
I'm going to back pedal a bit on this because I don't have a use case for this personally.

Contributions are more than welcome.  I'd love to support vanilla browsers, but I don't know how.  Besides packagers are now so prevalent.... and nowadays zero config is the buzz word du jour.
