### ISSUE TITLE
Android: timeout doesn't work when baseUrl is invalid

### ISSUE THREAD

**Issue by valloneflavio** [infinitered/apisauce#119]
Hi,
I have this configuration:

`  var api = create({
    baseURL: cfg.API_SERVER_URL,
    timeout: 6000,
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    }
  });`

And I use it as follow:
`
api.setHeaders({ // set headers to 'api' directly otherwise wont work
      'Accept': 'text/plain',
      'Content-Type': 'application/x-www-form-urlencoded'
    });

    return api.post(this.endpoint + '/startSession', `username=${user}&password=${pass}`)
      .then(res => res.data)
      .then((token) => {
        if (!token) { return null }

        if (token !== 'Invalid credentials') { // check if token is ok
          api.setHeaders({ // set headers to 'api' directly otherwise wont work
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'X-Tmr-Token': token
          })

          return token;
        }

        return false;
      });
  }
`

on iOs everythings work fine. on Android timeout function doesn't work.

Do you have any suggest?

Thanks in advance for your help!

**Comment by skellock** [comment]
I haven't experienced this at all.  Hopefully you're sorted.  Lemme know if this is still a blocker.  I'm guessing it's not since this is 5 months old.

**Comment by hungdev** [comment]
I get the same issue. anyone have the solution?
