### ISSUE TITLE
Content-Type not working at GET requests

### ISSUE THREAD

**Issue by fabiodiniz** [infinitered/apisauce#120]
I'm trying to make a GET request with a 'Content-Type' like 'application/vnd.api+json' and its not working, the content-type is not being changed. 😢 

```
const api = create({
  baseURL: 'http://localhost:3000',
  headers: {
    'Content-Type': 'application/vnd.api+json',
    'Accept': 'v1'
  }
})

api
  .get('users/token_exists', { confirmation_token: token })
  .then((response) => {
    console.log(response.status)
  })
```

**Comment by skellock** [comment]
With the third param of `.get` you can pass `{ headers: 'Content-Type': 'application/vnd.api+json' }`. Does that work?

How you're using it here is supposed to work though.

**Comment by fabiodiniz** [comment]
It looks like in GET requests, the Content-Type is not being sent. It makes sense because there is no payload in GET requests, only URL parameters (data is converted into parameters). Anyway, what I did to solve this problem is send an empty data object in axios config object.

> api.js
```
import { create } from 'apisauce'

const api = create({
  baseURL: `${process.env.API_BASE_URL}:3000`,
  headers: {
    'Content-Type': 'application/vnd.api+json',
    'Accept': 'v1'
  }
})

export default api
```

> anywhere
```
let payload = { id: this.recordView.id }

api
  .get('/record_views/touch', payload, { data: {} })
  .then((response) => {
    if (response.ok) {
      console.log('ok')
    }
    else {
      console.log('not ok')
    }
  })
```

**Comment by skellock** [comment]
Ugh, thx for the follow up!

**Comment by guziyu001** [comment]
hi,
I try to request something via get method like this
api.get('', null, { headers: { 'Content-Type': 'application/json; charset=utf-8' } })
and the Content-Type does work

**Comment by fabiodiniz** [comment]
You need to pass an empty `data` object, so the `Content-Type` will be sent . Idk why, but Axios don't send custom headers in `GET` requests when there is no `data` object.

Your code would look like this:
```
api.get('', null, {
  data: {},
  headers: {
    'Content-Type': 'application/json; charset=utf-8'
  }
})
```

**Comment by bunea** [comment]
@fabiodiniz This isn't actually a bug in either of the libraries though. The `Content-Type` header refers to the type of data you are sending to the server and as such there is no reason to send it if there's no body to the request. My guess is that you would want to use the `Accept` header which specifies how you want your response formatted.

This is what I think you're actually looking for:
```
const api = create({
  baseURL: 'http://localhost:3000',
  headers: {
    'Accept': 'application/vnd.api+json'
  }
})

api
  .get('users/token_exists', { confirmation_token: token })
  .then((response) => {
    console.log(response.status)
  })
```

**Comment by robinheinze** [comment]
I'm going to go ahead and close this since it seems like @bunea answered the question sufficiently.

**Comment by xforcarlos** [comment]
@fabiodiniz 
hey bro we found good solution for JSON API 
create interceptors and put config.data = null 
to every get request will send content type 

```
 this.apisauce.axiosInstance.interceptors.request.use((config) => {
      if (config.method == "get") {
        config.data = null
      }
```
