### ISSUE TITLE
Raw Data in body in post

### ISSUE THREAD

**Issue by paomosca** [infinitered/apisauce#125]
Goodmorning @skellock today i tried to connect with a weird old API that requires all connections in post with raw json data in body.

i tried in postman and it works, but i cannot make the same call with apisauce i'm trying:

api.post(ROUTEPOINT, data, {
      headers: { "Content-Type": "text/plain" }
    });

and i tried to put in data the data object and also the json.stringify object
both options failed.

any idea to make it works?

**Comment by paomosca** [comment]
no... i'm an idiot. forgive me... NSAppTransportSecurity...

**Comment by skellock** [comment]
Ha! Burned me so many times too! That and CORS. *raises clenched fist skyward*
