### ISSUE TITLE
How can I get the error number when an error happends on the backend? Label: help wanted

### ISSUE THREAD

**Issue by MaxiSantos** [infinitered/apisauce#127]
I'm seeing an NETWORK_ERROR when I'm trying to get a non existing resource in my server. I see on the dev console of chrome that the call returns a 404 error. However on error handler on apisause I only see NETWORK_ERROR. Where I can get the error number? I need to redirect my users to a 404 page only on 404 error.

**Comment by skellock** [comment]
It's `.status` on the response.

**Comment by MaxiSantos** [comment]
![image](https://user-images.githubusercontent.com/1896467/31628036-c6d26328-b285-11e7-9d8c-9b6b1d7a9460.png)

When the call is ok I see a 200 status code. But when I see a 404 on my dev console I don't see that error on the response in apiSauce.

**Comment by skellock** [comment]
`NETWORK_ERROR` means that it is unable to connect to the server to acquire a status code.

Can you confirm in `curl` or `postman` that you're getting a response back?

**Comment by MaxiSantos** [comment]
yes, I'm using postman and I see this error
![image](https://user-images.githubusercontent.com/1896467/31637841-06783ae0-b2a7-11e7-9e37-3c0af97630d0.png)

That "query parameter" is missing may be wrong because it's not needed. However, you see at the top that the status is 404. I'm not seeing a way to get that number.

**Comment by skellock** [comment]
I see what you're saying.

I see `webpack` in there. Which browser is this on?  Latest chrome on Mac?

Latest version of `apisauce` as well?

**Comment by MaxiSantos** [comment]
apiSauce: "version": "0.13.0"
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by skellock** [comment]
Does it work with `0.14.1`? That's the latest.

Also do you see anything in Chrome's network debugging panel?

**Comment by MaxiSantos** [comment]
ok, I'm using 0.14.1 and still seeing status with a null value.

This is the console log:

![image](https://user-images.githubusercontent.com/1896467/31642054-362ba4f8-b2bf-11e7-9afb-5956e665ab0c.png)

this is the expanded error log:

![image](https://user-images.githubusercontent.com/1896467/31642084-66e00954-b2bf-11e7-837a-cdcb7462f3d6.png)

and on the network tab I see the 404 error:

![image](https://user-images.githubusercontent.com/1896467/31642156-db364408-b2bf-11e7-8cbe-962273291419.png)

**Comment by skellock** [comment]
Ahh.. that CORS error is wrecking things here.  Do you get the same issue if you use `fetch`?

**Comment by MaxiSantos** [comment]
I'm sending a non-existing articleId to the server. It dosen't find it and therefore it returns an error plus the 404. But when I send an existing articleID then the server returns the correct data for the web to display. So, I don't think this is related with CORS because this is only happening when I send a non existing articleID.

When you say to try "fetch".. do you mean as a separate method from apisauce, right?
So, instead of
`javacsript`
api
		.get(url)
		.then(response => {

I should do:
fetch(url)
		.then(response => {

**Comment by skellock** [comment]
So, here's what I said it's CORS related:

![image](https://user-images.githubusercontent.com/68273/31692819-73450bea-b369-11e7-8aa0-216a55e22018.png)

I see those 404s coming back in your chrome console, but don't understand why it it would remove the status code.  Perha

Are you able to give me some repro steps?  I'd be happy to take a closer look. 

It really looks like your server is not responding with the proper HTTP Headers CORS needs to work when you receive a 4xx series issue.

**Comment by MaxiSantos** [comment]
hi, I was trying to comment long time ago but I got some errors in github while commenting. It turns out the backend wasn't returning correctly the errors so therefore apisauce was defaulting to NETWORK_ERROR.
