### ISSUE TITLE
unable to do a post request. 

### ISSUE THREAD

**Issue by rajat-np** [infinitered/apisauce#135]
I am able to do a post request to an API endpoint using request, but in case of apisauce , it keeps failing. and the error is 403.

**Comment by rajat-np** [comment]
I did use FormData() to create the form data and push the object in POST request, any help will be appreciated.  Thank you.

**Comment by skellock** [comment]
403 means forbidden.  Have a look at your authentication mechanism.  Often this is done via http request headers.

Also debugging this via reactotron or chrome dev tools can help because you can see exactly what is jumping the wire.

**Comment by rajat-np** [comment]
I was able to do solve the issue by modifying the request headers, thanks for pointing it towards request it.
