### ISSUE TITLE
Unable to configure request config for httpsAgent

### ISSUE THREAD

**Issue by zhakygng** [infinitered/apisauce#136]
Hi guys,

I have difficulties on configuring apisauce specific for httpsAgent.
What i want to achieve is, i want to the client to check certificate of secure service i accessing, more popular term is certificate pinning. Axios itself have support for this as explained [here](https://github.com/axios/axios/issues/284).

So here is what i try to do :
```javascript
var https = require(https);
// unable to load https module since it is built-in Node module
const api = apisauce.create({
	baseURL,
	headers: {
		'Cache-Control': 'no-cache',
		Accept: 'application/json',
		'Content-Type': 'application/json'
	},
	httpsAgent: new https.Agent({
		//public CER
		ca: 'cer-file.cer'
	}),
	timeout: 10000
});
```
I notice the problem is when i call https module which are built in node module.
```javascript
var https = require(https);
```
Is there other way to configure this to able to run in react-native apps?

There is [node.js http module substitution](https://github.com/tradle/react-native-http) for react-native, but i couln't find one for https.

**Comment by skellock** [comment]
I think something like this is much more difficult on React Native since it's not the browser that's enabling this functionality.

In React Native, the networking layer ultimately comes from native components (NSURLSession on iOS and okhttp on Android).

https://github.com/localz/react-native-pinch looks promising.  They seem to provide their own `fetch` call entirely to make this work.

If cert pinning is a hard requirement, I'd point you in their direction since it wouldn't be compatible with `axios` or `apisauce`.

I'm curious to hear how it goes, so lemme know if you have any success with this!

**Comment by zhakygng** [comment]
I tried several library to load node native module to able call http module like [node-libs-react-native](https://github.com/parshap/node-libs-react-native)(module not working while executing require.reload), direct load [https-browserify](https://github.com/substack/https-browserify) (still require native http module) but still unsuccessful. I not to familiar with this kind of method.

Since this is a hard requirement (i developing financial app that require this to be done to patch security finding of MITM attack) i will look for another options. 

Thanks a lot @skellock for your advice. [react-native-pinch](https://github.com/localz/react-native-pinch) looks promising, will try this right away.

**Comment by SamiChab** [comment]
Hey @zhakygng, could you try `react-native-pinch`? If so, can you give us a feedback please?

**Comment by zhakygng** [comment]
Hi @SamiChab, i already tried `react-native-pinch` on my project and successfully implementing certificate pinning.
Last time i work for this project is april last year, i couldn't verify if this is still working or not today. 
 
What i do is replacing all `apisauce` REST API call implementation with `react-native-pinch`. Also additional work on parsing `react-native-pinch` response & error to become `apisauce` compatible.

**Comment by SamiChab** [comment]
Thanks @zhakygng for your answer!

**Comment by worldofchu** [comment]
I want get a npm package https, because i can't download from the  npm addr
