### ISSUE TITLE
Possible Issue - Trouble creating consistently

### ISSUE THREAD

**Issue by GantMan** [infinitered/apisauce#137]
Version 2.6.2 of `tsc` has this issue with 0.14.3 release of apisauce.
```
$ /Users/gantman/Documents/Projects/cli/gluegun/node_modules/.bin/tsc -p .
node_modules/apisauce/dist/apisauce.d.ts(96,16): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.
```

version 2.5.3 of `tsc` does not have any issues.

This issue randomly happens, and switching back and forth between 0.14.2 and 0.14.3 changes things.  So wtf is this ticket about?   ummmmm....

FIRST!   yeah....

**Comment by skellock** [comment]
Yikes, I haven't encountered that yet.  What do you have for your `compilerOptions` in `tsconfig.json`?

**Comment by skellock** [comment]
Lemme know if you still have any problem or any details to track this down.

**Comment by mcanobbio** [comment]
Hi, I have the same issue with the same **TypeScript** version `2.6.2`

I have this config on `tsconfig.json`

```{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "jsx": "react-native",
    "sourceMap": true,
    "outDir": "./lib",
    "strict": true,
    "noUnusedLocals": true,
    "typeRoots": ["./src/types"],
    "types": ["react", "react-native", "jest"]
  },
  "include": ["./src/"]
}
```
