### ISSUE TITLE
Reusing HTTPS connections

### ISSUE THREAD

**Issue by tspecht** [infinitered/apisauce#138]
Hey!

I'm currently trying to make sure that `apisauce` and `axios` reuse once opened HTTPS connections to an external API I'm using to make sure that the SSL handshake is only done once per connection and not on every request.

Any idea on how to achieve this? Tried looking for `keep-alive` and similar in the documentation + code but couldn't find anything ...

**Comment by skellock** [comment]
I'm not sure.  There isn't anything in `apisauce` that would do it.  I don't remember seeing anything in `axios` either.

I don't see anything in the react native code base to support that either.  

https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411657-httpshouldusepipelining?language=objc

Lemme know if you do find out anything!

**Comment by tspecht** [comment]
Hey @skellock sorry for the possibly dumb question - how is this related to React Native? 🤔

**Comment by skellock** [comment]
Ha, sorry I assumed you're using React Native.  You're talking straight up browser then ya?

**Comment by skellock** [comment]
Gotcha, could you add a custom header for `CONNECTION: Keep-alive`?  Is that what your server is looking for?

**Comment by tspecht** [comment]
Hm it's actually not my own server, so not sure ... in general it would be important that the session is actually getting reused for multiple sequential requests, so this would probably also affect things like cookies etc. Basically looking for something similar to `requests.Session` in Python, works flawlessly there! http://docs.python-requests.org/en/master/user/advanced/

**Comment by williamchong007** [comment]
> I'm not sure. There isn't anything in `apisauce` that would do it. I don't remember seeing anything in `axios` either.
> 
> I don't see anything in the react native code base to support that either.
> 
> https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411657-httpshouldusepipelining?language=objc
> 
> Lemme know if you do find out anything!

FYI axios supports keep-alive via http(s) agents
https://github.com/axios/axios/issues/1846#issuecomment-434208900
Does similar solution exists for this package?
P.S. I am using react native
