### ISSUE TITLE
[Suggestion] withCredentials in API configuration

### ISSUE THREAD

**Issue by efournival** [infinitered/apisauce#139]
Hi,

I needed to specify the `withCredentials` field in my AJAX requests. I did it like that :
```JavaScript
const api = apisauce.create({ ... });
api.axiosInstance.defaults.withCredentials = true;
```

It would be nice if this was possible:
```JavaScript
const api = apisauce.create({
  ...,
  withCredentials: true,
  ...
});
```

What do you think?

**Comment by skellock** [comment]
Love it! Wanna hook us up with a PR?

**Comment by acharlop** [comment]
Just verified in my app and in the code `withCredentials: true` in the config works. Have you tried it?

**Comment by jkeam** [comment]
Is this something we can close?  Seems like it's all good?  :)
