### ISSUE TITLE
Retry request

### ISSUE THREAD

**Issue by mladen-m** [infinitered/apisauce#141]
I was not able to retry the request if it fails.

I added addResponseTransform like this:
`api.addResponseTransform(response => {
   if (!response.ok && response.status === 404) {
      tryToLoginAndRetry(response.config);
   }
}

function tryToLoginAndRetry(config){
   ??? // What to add here
}`

**Comment by skellock** [comment]
Not sure. I don't have any code that will fill in the blank there.

I'd personally move that code into an async workflow that lived outside the api.

We don't have an `asyncResponseTransform`, but perhaps if we did, you could essentially stall out the promise being resolved until you got the answer from your API you needed.

Still, that doesn't feel quite right (to me at least).

Keep us posted if you get a good beat on retrying.  Have a look at some pure axios solutions out there too, they apply here as well.

=)

**Comment by twelve17** [comment]
I am looking into this as well, and the best I can come up with is to come up with an axios interceptor, but then it would be basically omitting the "detect network issues" feature of this library, which seems odd too.  All this being said, how can I set an interceptor to the underlying axios instance?

**Comment by twelve17** [comment]
Never mind, I see now I can access it via `axiosInstance`

**Comment by jwrubel** [comment]
For anyone else who is in need of a retry solution and stumbles across this, I ended up using the [retry-axios](https://github.com/JustinBeckwith/retry-axios) library to handle an api that includes rate limits, like so:

```
const apisauce = require('apisauce')
const rax = require('retry-axios')
const api = apisauce.create({
  baseURL: [YOUR_BASE_URL_HERE]
})
const interceptorId = rax.attach(api.axiosInstance)
// now call your api as normal. Responses 100-199, 429, and 500-599 should be retried 3 times
api.get(...
```
The default config handles 429 but not 404, however the documentation for the library describes how to pass a config object to retry on different http statuses and a bunch of other parameters.

I hope this helps!
