### ISSUE TITLE
[How to] Put dynamic id to the url

### ISSUE THREAD

**Issue by thphuc** [infinitered/apisauce#142]
Hello,

I tried to find a way to put dynamic id to the url but not found yet.
The url is https://www.mydomain.com/{id}, {id} will be changed

I created function: 
`const getProductDetail = (id) => api.get('' + id)`

Then I call it like below:

> const endpoint = 'getProductDetail'
> const args = ['']
> this.api[endpoint].apply(this, args).then((result) => { }

I have no idea of how to put the dynamic id. Please give me suggestion. Thank you!

**Comment by skellock** [comment]
I think i'd create a new `api` with the right `baseURI` whenever that changes.

Maybe pass a function into the api that it can call to acquire said `id` (like dependency injection)?

Probably a lot of ways you could approach this.

**Comment by thphuc** [comment]
Hi @skellock 
Thank you for your suggestion.
I managed to solved it by using below code.

> const endpoint = 'getCheckpointDetail'
        const args = [code]
        this.api[endpoint].apply(this, args).then((result) => {}

I mean put the code to args without providing it a name
