### ISSUE TITLE
[Help] Different header on Android and iOS

### ISSUE THREAD

**Issue by jboteros** [infinitered/apisauce#143]
Hello, 

How to separate the header depending on the iOS or Android platform

Thanks!!!

**Work on iOS**
`const api = apisauce.create({
    baseURL,
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    timeout: 10000
  });`

**Work on Android**
`const api = apisauce.create({
    baseURL,
    headers: {
      "Content-Encoding": "gzip",
      "Cache-Control": "no-store",
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    timeout: 10000
  });`

**Comment by skellock** [comment]
In React Native, you'd use the `Platform.OS` to determine the platform.
