### ISSUE TITLE
Call two api at the same time return status code 0 ?

### ISSUE THREAD

**Issue by viper4595** [infinitered/apisauce#145]
Hi,

I have a problem, when i call two different api in componentdidMount of my react native app, one of them return status code 0 with no error or response, but it's ok when calling one by one (call one api and disable other).

**Comment by skellock** [comment]
Hard to guess what’s going on without seeing the code or traces in action. If you delay one by a few seconds does it work?

**Comment by viper4595** [comment]
Yes, it work if delay one by a few seconds. And it happen just on iOS, everything work fine on Android.

**Comment by skellock** [comment]
Oh boy.  That is super strange. I haven’t seen this issue. Do you have some code you can share?

**Comment by viper4595** [comment]
Hi and so sorry, i caught up with work and forgot to tell you the problem was from my server. Thank you for great support!

**Comment by skellock** [comment]
Glad you’re sorted!

**Comment by gregory-light-it** [comment]
@viper4595 what was that? I have similar problem with status code 0

**Comment by atominvention** [comment]
same issue, status code: 0, response: skipped
