### ISSUE TITLE
How to combine concurrent fetches of same api ?

### ISSUE THREAD

**Issue by iiitmanikanta** [infinitered/apisauce#148]
if a fetch is already pending, the next repeated requests made to the same api should return either latest or first response instance to all requests.

something similar to the **takeLatest** effect in _redux-saga_ 

is there any configure in apiSauce for this ?

**Comment by skellock** [comment]
That kind of intelligent caching would be a layer sitting on top.  This library is only for making API calls.

Good idea, just not the right fit for this library.
