### ISSUE TITLE
Network failures resulting in unhandled exceptions

### ISSUE THREAD

**Issue by peacechen** [infinitered/apisauce#151]
This may be due to changes in React Native 0.55, I'm not sure.  Our crash analysis tool is reporting these unhandled exceptions for a plain GET when the network connectivity is bad.

> node_modules/react-native/node_modules/whatwg-fetch/fetch.js   in listener at line 440:21
```
        options.url = 'responseURL' in xhr ? xhr.responseURL : options.headers.get('X-Request-URL')
        var body = 'response' in xhr ? xhr.response : xhr.responseText
        resolve(new Response(body, options))
      }
      xhr.onerror = function() {
        reject(new TypeError('Network request failed'))
      }
```

The events leading up to it:

> xhr
> GET https://my.api/someparam [0]
> 
> sentry
> TypeError: Network request failed
> 
> exception
> TypeError: Network request failed
> 

I saw this once in the debugger but forgot to capture the call & response.

**Comment by skellock** [comment]
I’ve yet to see this error. Are you using apisauce or fetch? Do you have some more code to share?

**Comment by peacechen** [comment]
Yes using apisauce.  It's a simple get request:
```
api.request.get( 'inventory/' + id );
```

Where `api` is an instance from apisauce's `create()`

**Comment by skellock** [comment]
I've been hanging back from 0.55 due to some outstanding bugs, but I'll give this a spin shortly.

In your example is `.request` the `apisauce` instance?

**Comment by peacechen** [comment]
Yes, sorry wasn't clear about that.  There's a wrapper class that creates the apisauce instance and assigns it to the `request` key.

**Comment by peacechen** [comment]
Investigated further with the debugger and found that it's `react-native-google-analytics` triggering the fetch exception.  Apologies for the confusion 🙏
