### ISSUE TITLE
`main` module field that could not be resolved

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/apisauce#157]
After upgrading to the latest apisauce 0.15.0 started to receive that error, downgraded back to 0.14.3

**Comment by vaughankg** [comment]
👀 
```
$ ls node_modules/apisauce
LICENSE      README.md    package.json
```
It's a :ghost: town in there.

**Comment by Amurmurmur** [comment]
@vaughankg ahaha, yeah I've noticed that, so reverted back lol

**Comment by skellock** [comment]
woah... haha!  

You didn't read the change log?

`* [new] literally deleted myself`

I'll fix this now.

**Comment by skellock** [comment]
I don't often deploy to production.  But when I do, it's on a Friday.

0.15.1 is now available.
