### ISSUE TITLE
onDownloadProgress catching an error [SyntaxError: JSON Parse error: Unexpected identifier "object"] line: 114, column: 38

### ISSUE THREAD

**Issue by zxccvvv** [infinitered/apisauce#170]
I'm just read the [closed issue](https://github.com/infinitered/apisauce/issues/59),

when I'm add below code:
```
api.get('myUrl', {onDownloadProgress: value => console.log(value)})
.then((response)=> {
  console.log(response)
})
.catch((err)=>{
  console.log("axios cathing error")
  console.log(err)
})
```

I got this error :
![image](https://user-images.githubusercontent.com/19633881/43563007-34bc44c8-964a-11e8-924b-95f827ee1da3.png)

How can I solve the issue?

**Environment:**

apisauce | ^0.14.3

**Comment by skellock** [comment]
Looks like the server is sending you unparsable json.  Line 114, column 38.

**Comment by zxccvvv** [comment]
@skellock It's not about my server didn't sending me unparsable json, 

because the [apisauce giving another `param` before the `AxiosRequestConfig`](https://github.com/infinitered/apisauce/blob/master/apisauce.d.ts#L88)

adding `null` and the code look's like:
```
var config = {
  onDownloadProgress: function(progressEvent) {
    console.log(progressEvent.total)
    console.log(progressEvent.loaded)
  }
}
api.get('myUrl', null, config)
.then((response)=> {
  console.log(response)
})
.catch((err)=>{
  console.log("axios cathing error")
  console.log(err)
})
```

but `progressEvent.loaded` value is `0`, and `progressEvent.total` giving me `547242`,

how can i get progressEvent.loaded value?

**Comment by skellock** [comment]
Ah... yes, we pass the 3rd param over to `axios` directly.

I'm not too sure about the progress event stuff.  We don't touch that in this library.  

I think in the past, I've used it with react-native on android and had problems.  That was 20 some versions ago, and I'm sure a lot has changed.

Sorry I can't be of more assistance.  I just don't use that feature at all.
