### ISSUE TITLE
Uploading Images

### ISSUE THREAD

**Issue by razvantodea14** [infinitered/apisauce#183]
I am trying to upload an image using "apisauce": "0.16.0"
This is the code used:
`    const data = new FormData();
    data.append('', {
      uri,
      type: 'image/jpeg',
      name: 'profileImage',
    });
    return api.post('Account/UploadProfilePicture', data, { headers: { ...api.headers, 'Content-Type': 'multipart/form-data' }});`
I've also tried to remove Content-Type, but with no luck. 

This is how the response looks like. I believe that the request is not formatted well and the apisauce tries to send the data as Application/Json.

![screen shot 2018-09-06 at 11 48 23](https://user-images.githubusercontent.com/39618488/45146364-68d3f980-b1cb-11e8-9862-69e3936f9e10.png)

Is this a bug or something is missing in my code?

**Comment by SalahEddineBC** [comment]
add 'Accept':'multipart/form-data' in your header
