### ISSUE TITLE
Possible event loop starvation?

### ISSUE THREAD

**Issue by borgand** [infinitered/apisauce#184]
I have been using `apisauce-0.6.0` in two solutions deployed into a factory:

* a headless Raspberry PI monitoring some sensor and sending the events to cloud API
* a React Native app on Android periodically syncing to cloud API and displaying various information.

The factory setting is out of our direct control and we can't vouch for the WiFi quality, but on average the connectivity is good.

First, the Raspi started developing an issue – at times it would "miss" some interrupts from the hardware. Digging into it seemed to indicate bad network at the time – logs showed that syncing also did not receive responses from server until an `UNKNOWN_ERROR` was logged.
At that time it seemed to me that `apicause` (or dependencies of it) is starving the event loop with `on NextTick()` somehow. I had to get the stuff working, so as a workaround I rewrote the interrupt monitoring in Ruby, that passes events to JS script to sync to server – seems to work good enough.

Now, the Android app is developing similar issues – it is syncing every 5 seconds to the server (server response is measured and takes ~0.2 sec to create). Again, occasionally the app *freezes totally* for long periods of time, which we haven't been able to reproduce in our dev setup, only in that factory. During this freeze, the server also does not receive any sync requests from the app.

Is it possible that in some bad/weird network situations `apisauce` or some network stack starves the JS event loop, causing it to be non-responsive to touches, etc?

Is there any debugging that I could do to dig deeper into it?

**Comment by borgand** [comment]
I will look into upgrading to `0.16` and see if we can get to the bottom of this.

We do have somewhat largeish JSON, but not megabytes large. We have noticed that just receiving the JSON takes a while (1-2 sec for the whole sync operation). We also use `seamless-immutable` for the work. I will look into this too.

Why I suspect event-loop starvation is that the difference between two payloads is minimal, so if it works for several hours/days and then suddenly chokes, it's hard to blame the payload processing which is monotonous, but rather some external conditions that have changed.

One other thing that I just remembered – we recently had an issue where the RN code died mysteriously and it turned out that the Redux state was corrupt (one key was missing) and only way this could have happened is if `apisauce` returned a `response.ok == true` but `response.data.mykey == undefined` but our server always puts this key in a successful response. We implemented a protection that avoids storing corrupt state, but it is still interesting how can a successful response not contain expected data.

Thanks for the pointers.

**Comment by skellock** [comment]
I was using `seamless-immutable` as well.

Any `200` series response with make a `.ok === true` state.  This includes `204`.  It really depends on what the server sends.  Always check your `response.data` though.  Even `dispatch('event', { ...response.data })` is better than nothing =)

**Comment by robinheinze** [comment]
@borgand Just checking up on this...did upgrading to 0.16 get you any answers?
