### ISSUE TITLE
import CancelToken from apisauce

### ISSUE THREAD

**Issue by ahce** [infinitered/apisauce#185]
## Expected behavior
```
import { CancelToken } from 'apisauce';

const { source } = CancelToken;
const { cancel, token } = source();

```

## Actual behavior
```
import axios from 'axios';

const { CancelToken: { source } } = axios;
const { cancel, token } = source();

```
 
## Environment

| Tech                | Version |
|---------------------|---------|
| apisauce | 0.16.0 |
| react | 16.5.2 |

**Comment by skellock** [comment]
Ya, that sounds reasonable.  Up for a PR?

**Comment by ahce** [comment]
@skellock the PR is ready: #186
