### ISSUE TITLE
Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.

### ISSUE THREAD

**Issue by steelegg** [infinitered/apisauce#189]
I set baseUrl according to the document method. I have already set proxy,But cross domain has occurred.
![image](https://user-images.githubusercontent.com/32324541/46741788-52442500-ccd8-11e8-9b97-77b598dddcb4.png)
![image](https://user-images.githubusercontent.com/32324541/46741819-61c36e00-ccd8-11e8-90de-459a08656def.png)

**Comment by robinheinze** [comment]
Hey @steelegg! The error you got is indicating that the `Access-Control-Allow-Origin` header is missing. You would need that header since you are requesting a resource at a different domain (http://192.168.1.199) than your webpage is on (http://localhost:8081).

**Comment by steelegg** [comment]
> 嘿@steelegg！您收到的错误表明`Access-Control-Allow-Origin`标题丢失。您需要该标头，因为您在不同的域（http://192.168.1.199）请求资源而不是您的网页（[http：// localhost：8081](http://localhost:8081)）。
Thank you for your reply
I have set header in create. But this mistake still exists.
like this:
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods": "POST, GET, OPTIONS, DELETE",}

**Comment by gustavonecore** [comment]
I have the same issue. I have added the related headers for the OPTION method as well, but I'm still getting that CORS error.


- Preflight OPTIONS call

![image](https://user-images.githubusercontent.com/6432827/58609205-c423ab80-8274-11e9-8539-2eca5877eb68.png)

- POST endpoint

![image](https://user-images.githubusercontent.com/6432827/58609241-e87f8800-8274-11e9-90d5-b7a332c8553e.png)


And the related error in the console:

![image](https://user-images.githubusercontent.com/6432827/58609266-00efa280-8275-11e9-8104-96646210f9ea.png)


I'm kind out of ideas at this point :(

Any idea?
