### ISSUE TITLE
Return promise error in api transforms

### ISSUE THREAD

**Issue by nguyenhoanglam** [infinitered/apisauce#190]
I use redux-saga to call api methods and try-catch these methods in sagas. I want to return an error from the api transforms to sagas try-catch . It looks like this:

```java
  api.addResponseTransform(response => {
    if (!response.ok && response.problem) {
      const error = "Unknown error";
      return Promise.reject(error);
    }
  });
```

Any sample code for this?

**Comment by ryanlntn** [comment]
@nguyenhoanglam I don't have any sample code for that. In general we don't use promise rejection to represent API errors but instead rely on using the `ok` and `problem` properties in the resolved response mapping all possible api responses in one big discriminated union and handling that in an API service that wraps apisauce. If you would like to receive a promise rejection I'd recommend taking a similar approach. For example:

```
class API {
  constructor(config = DEFAULT_API_CONFIG) {
    this.config = config
  }

  setup() {
    this.apisauce = create({
      baseURL: this.config.url,
      timeout: this.config.timeout,
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
    })
  }

  get(path, params = {}, opts = {}) {
    const response = await this.apisauce.get(path, params, opts)
    return new Promise((resolve, reject) => {
      if (!response.ok && response.problem) {
        const error = "Unknown error"
        reject(error)
      } else {
        resolve(response)
      }
    })
  }

  // ... etc.
}
```

**Comment by nguyenhoanglam** [comment]
@ryanlntn Thanks for your code. I solved my issue!

**Comment by vfonic** [comment]
I'm trying to switch from axios to apisauce and I have my axios configured to handle errors "globally", as-in:

```js
    api.interceptors.response.use(
      response => response,
      error => {
        if (isNetworkError(error)) {
          toast('No network connection', { type: toast.TYPE.ERROR });
        } else if (isAuthenticationError(error)) {
          toast({ title: 'Authentication Error.', description: 'Please login again.' });
          props.auth.logout();
        } else {
          const errorMessage = get(error.response, 'data.message') || UNKNOWN_ERROR;
          toast(errorMessage, { toastId: errorMessage, type: toast.TYPE.ERROR });
        }
        return Promise.reject(error);
      });
```

In my API calls, I can just do:

```js
api.post(recordData).then(record => console.log(record.id));
```

But, when I'm trying to switch to apisauce, I don't have this kind of API available anymore. What's the best way to go about this? I don't want to have to write the if-checks all over the place:

```js
api.post(recordData).then(response => {
  if (response.problem !== null) return;

  console.log(response.record.id));
}
```
