### ISSUE TITLE
Add query string param support for POST

### ISSUE THREAD

**Issue by jsphstls** [infinitered/apisauce#191]
POST requests are allowed to have query string parameters but I see now way to do this in apisauce. Since POST allows a "data" property, why not also support a "params" property that affects the query string.

**Comment by robinheinze** [comment]
The third parameter is a config object passed to axios, and it overrides everything. So if you need to pass params, you should be able to do something like:

`apisauce.post("https://example.com", { myData: {} }, { params: { myQuery: "foo" }})`

The full list of options available in this config object can be found in the Axios docs (https://github.com/axios/axios#request-config)

**Comment by jsphstls** [comment]
Thanks @robinheinze , I'm glad there is a workaround. Is this something that can be directly supported by ApiSauce in the future rather than using the override ?
