### ISSUE TITLE
Latest release does not match npm

### ISSUE THREAD

**Issue by jonmann20** [infinitered/apisauce#193]
Latest GitHub release is v0.16.0.  Latest npm release is v1.0.0.

Were there any breaking changes?

**Comment by robinheinze** [comment]
There are release notes in the README [here](https://github.com/infinitered/apisauce#release-notes), but I can add an official tag and release as well. I don't believe 1.0.0 had breaking changes, @skellock just wanted to bump to 1.0.0 since the library is stable.
