### ISSUE TITLE
Use with TypeScript

### ISSUE THREAD

**Issue by SKEPDIMI** [infinitered/apisauce#197]
Hello! I've been trying to use apisauce with TypeScript. On making requests and receiving responses, however, I can't access the response.body object's properties. Example:

```
api.get('/hello')
.then(res => {
  const { ok, data } = res;

  if (ok) {
    console.log(data.myStuff);
    // property 'myStuff' does not exist on type {}.
  }
});
```

I'm new to TypeScript but I can't find anything written for apisauce so I thought it would be helpful to post it on here.

Thanks for the awesome tool!

**Comment by robinheinze** [comment]
@SKEPDIMI Does it work if you specify the `ApiResponse` type for your `res` argument in the promise resolution?

```
import { ApiResponse } from 'apisauce'

api.get('/hello')
.then((res: ApiResponse) => {
  const { ok, data } = res;

  if (ok) {
    console.log(data.myStuff);
    // property 'myStuff' does not exist on type {}.
  }
});
```

**Comment by SKEPDIMI** [comment]
Hello @robinheinze . I've specifying the ApiResponse type bring up this error:
```
-
Generic type 'ApiResponse' requires 1 type argument(s).
(alias) type ApiResponse<T> = ApiErrorResponse<T> | ApiOkResponse<T>
-
```

**Comment by robinheinze** [comment]
Oh right, I think you can just do `ApiResponse<any>`

**Comment by SKEPDIMI** [comment]
This corrected the issue, thanks a ton, @robinheinze !

**Comment by devpenzil** [comment]
> Oh right, I think you can just do `ApiResponse<any>`

What should I do instead of `<any>` type
