### ISSUE TITLE
add AsyncStorage data to response using addResponseTransform

### ISSUE THREAD

**Issue by navneetccna** [infinitered/apisauce#198]
Hi,

I want to add some data in my api response from AsyncStorage, so I am using addResponseTransform.

Now my code working fine but didn't get value in my response as AsyncStorage taking some time to get data and addResponseTransform not waiting for AsyncStorage to complete.

Can you please provide some solution that how addResponseTransform wait for AsyncStorage to complete?

**Comment by navneetgarggate6** [comment]
Please reply and provide any solution.

**Comment by navneetccna** [comment]
I tried that solution and getting error. Is there any other solution ?

**Comment by Nahani** [comment]
Hello, 
@robinheinze  the pull requesst https://github.com/infinitered/apisauce/pull/195 has been closed without merge...
Have you any news about a AddAsyncResponseTransform ?

Regards

**Comment by robinheinze** [comment]
@Nahani There's a different open PR which addresses the same issue https://github.com/infinitered/apisauce/pull/203. Maybe you can work with @navneetccna to get it updated

**Comment by navneetccna** [comment]
@robinheinze I created new pull request please check and verify.
#227

**Comment by robinheinze** [comment]
Fixed in #227 and released as part of 1.1.0
