### ISSUE TITLE
Add create config option for custom axios instance

### ISSUE THREAD

**Issue by sky-code** [infinitered/apisauce#205]
I use axios from ```@nuxtjs/axios``` and I want to pass already created and configured axios instance in  ```apisauce```.
At this moment axios instance created from config parameters and then used by local ```instance``` variable, so this instance can't be changed.
src: https://github.com/infinitered/apisauce/blob/master/lib/apisauce.ts#L135
Can we add optional config parameter ```axiosInstance``` and then check if it set, use it, otherwise create new axios instance.
```javascript
export const create = config => {
  let instance = config.axiosInstance
  if(!instance){
    instance = axios.create(combinedConfig)
  }
}
```

**Comment by robinheinze** [comment]
The is in 1.0.5
