### ISSUE TITLE
Retry request with new token data

### ISSUE THREAD

**Issue by adamgajzlerowicz** [infinitered/apisauce#206]
I'd like to get flow as follows:
- api call is made with expired token
- response transform catches that 
- new token is obtained
- original request is re-tried with new token

I am trying to find a way to do this but no luck :( can you please advice how to do this?

May thanks!

```
api.addResponseTransform(async response => {
  if (response.data.code === 401) {
    const newToken = await myApi.getNewToken({refreshToken: 'xxx'})

    // here I have new token and I'd like to use orignal config to re-attempt request
    const originalConfig = response.config
    const newResponse = await api.?????(originalConfig)

    // and then return new response as oginal response
    // so probably something like
    response = newResponse
  }
}
```

**Comment by adamgajzlerowicz** [comment]
After some investigation, I tried to use axios instance to retry the original response with modifications like this: `await api.axiosInstance.request(newConfig)`, which did get the data, but it seems that `addResponseTransform` will not wait for async actions. Your docs do say that `Data is the only option changeable.` So I will be changing my strategy and move the logic to `addRequestTransform`

**Comment by messenja** [comment]
Faced in with the same problem. Resolved with axios-auth-refresh package. Just connect interceptor to api.axiosInstance

**Comment by vankhoa01** [comment]
@messenja : Thank you for your suggestion
Could you please give me example code ?
Thank you

**Comment by messenja** [comment]
@vankhoa01 
`const api = apisauce.create({
		baseURL: AppConfig.baseURL,
		headers: {
			'Cache-Control': 'no-cache',
			'Content-Type': 'application/json; charset=UTF-8',
			Accept: 'application/json',
		},
	});

	const refreshAuthLogic = failedRequest => {
		console.log('Token has expired');
		return api.get(`${your-refresh-token-endpoint}`)
		.then(tokenRefreshResponse => {
			if (tokenRefreshResponse.ok) {
				const newToken = tokenRefreshResponse.data.token;
				api.setHeader('token', newToken);
				failedRequest.response.config.headers.token = newToken;
				store.dispatch(authActions.getTokenSuccess(token));
			} else {
				store.dispatch(authActions.getTokenError(tokenRefreshResponse.problem));
				console.log('Error while refreshing token: ' + tokenRefreshResponse.problem);
			}
			return Promise.resolve();
		});
	};

	createAuthRefreshInterceptor(api.axiosInstance, refreshAuthLogic);
`

**Comment by bytesagar** [comment]
@adamgajzlerowicz  How did you achieve retry function?

**Comment by adamgajzlerowicz** [comment]
Code from 2018 😄  Enjoy

https://github.com/adamgajzlerowicz/skeletoon/blob/master/frontend/src/state/fetch.js#L5

```
const customFetch = url => (uri: string, options: *) => {
    this.refreshingPromise = null;

    const initialRequest = fetch(uri, options);
    return initialRequest.then(response => (response.json())).then((json) => {
        if (json && json.errors && json.errors[0] && json.errors[0].message === 'Incorrect token') {
            if (!this.refreshingPromise) {
                const refreshToken = localStorage.getItem('refresh') || '';

                this.refreshingPromise = fetch('http://localhost:4000', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ query: `mutation { refresh(token: "${refreshToken}") { token } }` }),
                })
                    .then(e => e.json())
                    .then((response) => {
                        if (response.data && response.data.refresh && response.data.refresh.token) {
                            localStorage.setItem('token', response.data.refresh.token);
                            return response.data.refresh.token;
                        }
                        localStorage.clear();
                    });
            }
            return this.refreshingPromise.then((newAccessToken) => {
                this.refreshingPromise = null;

                // eslint-disable-next-line
                options.headers.token = newAccessToken;
                return fetch(uri, options);
            });
        }

        const result = {};
        result.ok = true;
        result.text = () => new Promise(((resolve, reject) => {
            resolve(JSON.stringify(json));
        }));
        return result;
    });
};
```

**Comment by imricky** [comment]
```javascript
this.apisauce.addAsyncResponseTransform(async response => {
 if(response.data.code === 401 || response.data.code === 403){
     const refreshToken = await storage.loadString("refreshToken")
     const data = await this.apisauce.post(`/login/refresh/token`, {
       refreshToken: refreshToken,
     })
     const res = data.data;
     if (!res.success) {
       // if refreshToken invalid, logout 
       logout(res)
     } else {
       const authToken = res.data,token;
       this.apisauce.setHeader("token", authToken)
       // retry
       const data = await this.apisauce.any(response.config)
       // replace data
       response.data = data.data;
     }
 }
})
```

it works for me

**Comment by yelderiny** [comment]
@imricky 

How would you then logout the user from the app if the request fails?
