### ISSUE TITLE
NETWORK ERROR returned when trying to add an Array to a FormData object, yet request is actually done

### ISSUE THREAD

**Issue by nyenye** [infinitered/apisauce#208]
So today I was adding a field to a POST request which had to be an Array, and I forgot to serialize it to JSON, and while apisauce was returning me {ok === false, problem === NETWORK_ERROR} the actual call was being made, and executed on backend.

**Comment by ryanlntn** [comment]
@nyenye This sounds like expected behavior to me except I would expect a different problem code. Can you create a minimal reproduction?
