### ISSUE TITLE
Access reducer from Api.js

### ISSUE THREAD

**Issue by leonardo2204** [infinitered/apisauce#210]
Hi guys, quick question, is it possible to access the redux store from the Api.js file?
My point is, I use redux-persist, so I always have my token set in a reducer called `auth`.
I'd like to know if there is a simple way to access it, kinda like:

```
api.addAsyncRequestTransform(request => async () => {
    const token = await getLocalToken() <- Here should be some kind of Selector
    if(!!token){
      request.headers['Authorization'] = `Bearer ${token}`
    }
  })
```
I know I can always save the token in the AsyncStorage, but since redux-persist is doing that for me, I don't want to manage this "token lifecycle" myself.

Thanks!

**Comment by danielqa** [comment]
I have the same issue. +1
