### ISSUE TITLE
HTTP response is filtering some fields

### ISSUE THREAD

**Issue by leon-developer-br** [infinitered/apisauce#231]
Hi, when I fetch some data from my server, some fields of the response are beeing filtered.

I created another app only with Axios and I can grab all header fields. Someone can help me?

**Comment by robinheinze** [comment]
Hey  @leon-developer-br, sorry you're having trouble! Would you mind giving us some more information about your code, preferably a minimal repro example (https://snack.expo.io/  is great for this)?

**Comment by leon-developer-br** [comment]
Sorry @robinheinze . My fault on opening this issue.
