### ISSUE TITLE
On failed requests, problem is always UNKNOWN_ERROR and fields set to null

### ISSUE THREAD

**Issue by rcstanciu** [infinitered/apisauce#243]
Hello,

Since I've upgraded to React Native 0.62.2, I have encountered a strange behaviour with apisauce. Each API request that fails has `problem: UNKNOWN_ERROR` and `originalError: {}` and all other fields set to `null` (like status, headers).

Below is a screenshot from Reactotron with the actual request that failed with error `400` and the response got from apisauce.

<img width="1146" alt="Screenshot 2020-06-18 at 15 14 34" src="https://user-images.githubusercontent.com/1048185/85018883-94dd2680-b176-11ea-9665-5f1767745b49.png">

apisauce: v1.1.1
axios: 0.19.0

**Comment by osamaq** [comment]
Are you adding any response or request transforms? If a throw happens there, this is the kind of error you get in my experience.

**Comment by rcstanciu** [comment]
Thank you for your quick response. It didn't cross my mind to check my interceptors.

Indeed, I have an interceptor for retrying failed requests:

```javascript
const onError = (err) => {
  const retryConfig = err.config.retryConfig;
  retryConfig.currentRetryAttempt = retryConfig.currentRetryAttempt || 0;

  const retryRanges = [
    [100, 199],
    [429, 429],
    [500, 599],
  ];

  // Check if should retry request
  if (retryConfig.currentRetryAttempt > 3) {
    return Promise.reject(err);
  }
  // Check if request is in retry ranges
  if (err.response && err.response.status) {
    let isInRange = false;
    for (const [min, max] of retryRanges) {
      const status = err.response.status;
      if (status >= min && status <= max) {
        isInRange = true;
        break;
      }
    }
    if (!isInRange) {
      console.log('Request not in retry-able requests range. Rejecting the promise...');
      return Promise.reject(err);
    }
  }

  const delayPromise = new Promise((resolve) => {
    const delay = ((Math.pow(2, retryConfig.currentRetryAttempt) - 1) / 2) * 3000;

    retryConfig.currentRetryAttempt += 1;
    setTimeout(resolve, delay);
  });

  return Promise.resolve()
    .then(delayPromise)
    .then(() => {
      return retryConfig.instance.request(err.config);
    });
};
```
After a quick trial and error, I managed to discover that my my issue comes from the first two lines:

```javascript
const retryConfig = err.config.retryConfig;
retryConfig.currentRetryAttempt = retryConfig.currentRetryAttempt || 0;
```

Apparently when I'm trying to change something inside error's config object, it gets messed up. What I was trying to do was to set the current retry attempt to the error's config, which should be like an `AxiosRequestConfig` object and use the original axios instance to retry the request. I've set the original axios instance in the following way

```javascript
  apisauceInstance.axiosInstance.defaults.retryConfig = {
    instance: apisauceInstance.axiosInstance,
  };
```

which I'm not sure if it's the cleanest way of achieving my goal.

Thank you for pointing that out. It helped me a lot! I will be looking to other ways of retrying my requests.
