### ISSUE TITLE
Get request with raw body

### ISSUE THREAD

**Issue by archansel** [infinitered/apisauce#244]
I'm trying to sent get request with payload as raw body, something like
```
curl --location --request GET 'http://0.0.0.0:10007/getlogin.api' \
--data-raw '{
	"payload" : "welORaMLzAySDZZTlHsn20rvXDCDXtSSV/Wrnxkc1JbVIM6OrjMddQ4Wkww/DvRT0glPGwYWJaqAQyp8tsycLTeZ7uxjx12tsKew38uT8rjHDg5z6gKCPnK956eaPfCe"
}'
```

 I tried using `this.apisauce.get(Endpoints.login, {}, { data: result.data })` but it's not working, is there any way to send raw body in get?

**Comment by jamonholmgren** [comment]
Hi @archansel, sorry about the delay. Did you get this figured out?

**Comment by archansel** [comment]
Yes I did, but don't really remember how, the project was finished a long time ago
