### ISSUE TITLE
Upload size for picture - EntityTooLarge

### ISSUE THREAD

**Issue by MayoudP** [infinitered/apisauce#245]
Hello,

I'm using an apisauce request `POST /presignedUrl` in order to upload picture with a pre signed URL on S3. 
However, after getting the pre signed URL, I'm getting this error when doing the final `POST call`...
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>EntityTooLarge</Code>
<Message>Your proposed upload exceeds the maximum allowed size</Message>
<ProposedSize>710336</ProposedSize>
<MaxSizeAllowed>709960</MaxSizeAllowed>
...
```

This is how my request looks like : 

```
params : FormData() with the needed fields (Key, bucket, ...) I previously got by getting the pre signed URL.

api.post(presignedUrl, params, {
      headers: {
        Accept: "multipart/form-data"
      }
    });
```

Everythings looks good on the config of the request ? Do you have any ideas ?

**Comment by sharifhh** [comment]
This is a configuration in S3 for the maximum allowed size my friend.
You can change it from your S3 Post Policy in content-length-range
