### ISSUE TITLE
Cancellation Request

### ISSUE THREAD

**Issue by Jonofat** [infinitered/apisauce#246]
Sorry, I know this isn't actually an issue but I was hoping that you could include how to perform a cancellation request in the documentation.

**Comment by sharifhh** [comment]
You are welcome to submit a PR to update the documentation my friend.
You can also search for axios cancellation request, since apisauce is just a wrapper over axios

**Comment by makejun168** [comment]
Yes, I hava same question about how to perform a cancellation request , I already read the document but I cannot found, so I hope that documentation will be update soon

**Comment by NarasimhaReddyY** [comment]
Hello everyone,

Documentation missed this part. But Kindly check this snippet [Creating Cancellation using apisauce](https://github.com/infinitered/apisauce/blob/7265ae3ab7599ff36502890a3e5f5a7b30a40902/test/cancellation.test.js)

Its working greatly.
