### ISSUE TITLE
APIs are not called in background - ios

### ISSUE THREAD

**Issue by m-tbox** [infinitered/apisauce#248]
**What's going on?**
- I have used apisauce in ios app made in react native 
- I have an api that uploads images it works fine in foreground 
- However if submit the form and take the app to background the form is not submitted to server. 
- I am also using redux-saga 
- I have added debugger before and after api call in saga 
- in background mode  saga doesn't receive any response from the api

---
**Steps to reproduce**
- Submit form at a POST api 
- Bring the app to background 
- Form  will not be submitted to server (Saga also don't receive any response back)
- I have tested in iPhone 11, OS 13.3
---

Please help me how can I call post apis in background for ios using redux-saga

**Comment by sharifhh** [comment]
This is a limitation in iOS, you should enable background processing and use a library that supports background uploading, I would recommend using this library: https://github.com/Vydia/react-native-background-upload

**Comment by chakrihacker** [comment]
closing this issue with above suggested solution
