### ISSUE TITLE
dont send cookie in first request ios

### ISSUE THREAD

**Issue by alireza847-programmer** [infinitered/apisauce#253]
const api = create({
  withCredentials: true,
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json;charset=UTF-8',
    'Access-Control-Allow-Credentials':true,
    'Access-Control-Allow-Origin': '*',
  },
});

**Comment by chakrihacker** [comment]
Closing issue as there is no good explanation. Feel free to open again with some steps to reproduce
