### ISSUE TITLE
Remove ramda dependency

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/apisauce#254]
Ramda brings about half a meg of dependency. Let's replace it with bare javascript helpers.

**Comment by markrickert** [comment]
Yikes! looks like its' pretty heavily used: https://github.com/infinitered/apisauce/blob/e439ab8558a0a5af17c69f4202723c6227c6f0fc/lib/apisauce.ts#L2-L21

**Comment by rfigueroa-truelogic** [comment]
ramda gziped uses 13kb so we can close this ticket @jamonholmgren
