### ISSUE TITLE
originalError": [TypeError: undefined is not an object (evaluating 'r.config')] when backend returns HTTP 400.

### ISSUE THREAD

**Issue by esbenvb** [infinitered/apisauce#271]
When the username/password is fine, it works as expected. 

But I want to detect an HTTP 400 error from the backend API, and use the returned error to improve the user experience, when the password is wrong.

But the unknown error I get back as seen below, is pretty much useless, and I also wonder what `r.config` refers to.

![image](https://user-images.githubusercontent.com/426051/129594200-b476997d-e97d-48a0-9ff2-1f52043ae154.png)

I make the requst below using newest 2.1.1 apisauce version, but had the same result with 1.1.2.

```js
    this.authApi.post(
      'token',
      'device_id=55....-A2F7-42D302&grant_type=password&password=qwerty&username=45...71',
      {
        headers: {
          Authorization:
            'Basic Ym9zakFwcDo1MGZkYWIzN......mYTQ4',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
```

The response from the promise returned by the request. when I log it to the console:
```json
{
  "config": null, 
  "data": null, 
  "duration": 3687, 
  "headers": null, 
  "ok": false, 
  "originalError": [TypeError: undefined is not an object (evaluating 'r.config')], 
  "problem": "UNKNOWN_ERROR", 
  "status": null
}
```

**Comment by jamonholmgren** [comment]
I tried replicating this but it was difficult to do. Could you let me know the easiest way to replicate what I'm seeing here?

**Comment by esbenvb** [comment]
> I tried replicating this but it was difficult to do. Could you let me know the easiest way to replicate what I'm seeing here?

I think I found the issue - there was an interceptor in the code base, which didn't return the error properly after logging it

```js
  instance.interceptors.response.use(
    (response) => {
      interceptorLogger.log(printResponse(response))
      return response
    },
    (error) => {
      interceptorLogger.log(printResponse(error))

      return error // I added this line and now it works as expected
    }
  )
```

**Comment by jamonholmgren** [comment]
It would be nice if axios gave a better error there, but glad you got it figured out!
