### ISSUE TITLE
Latest issue on npm is 1.1.5 instead of 2.1.5

### ISSUE THREAD

**Issue by shobhitsinghal624** [infinitered/apisauce#286]
The 1.1.5 release set it as the latest version in npm. It should be 2.1.5.

**Comment by jamonholmgren** [comment]
Good catch!

**Comment by jamonholmgren** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1479215/151074842-22286746-f5b8-42ff-b2fa-9b12e51358f0.png)
