### ISSUE TITLE
Update axios dependency to pick up vulnerability

### ISSUE THREAD

**Issue by eithe** [infinitered/apisauce#287]
The follow-redirects package which is a dependency of axios 0.21.4 is vulnerable; https://github.com/advisories/GHSA-74fj-2j2h-c42q.

Any chance you could update the axios dependency all the way to latest [0.25.0](https://github.com/axios/axios/releases/tag/v0.25.0)?

**Comment by ardasatata** [comment]
I've forked the repo and tried to update the axios, seems working properly & the test case doesn't seems to have any problem.

These are the dependencies that I update in my repo
```
"axios": "^0.25.0",
"@types/node": "15.6.1",
"typescript": "3.9.4"
```

here is the link to the package.json :
[package.json](https://github.com/wilopo-cargo/apisauce/commit/95b7763f957e0d8caf941952a1722347287870f5)

hope it helps 🙏
