### ISSUE TITLE
is there any schedule to upgrade the axios?

### ISSUE THREAD

**Issue by EricLiuZero** [infinitered/apisauce#305]
Thanks to all contributors, I really enjoyed fetching data using apisauce. It provides trivial and easy way to process response data.
However, I was challenged that the version of dependency `axios` remains `0.21.4` by teammates.
![image](https://user-images.githubusercontent.com/3775020/223359965-265f632e-7d9f-4009-9b4f-375cbf633dc2.png)
In addition, sometimes, the definition of typescript doesn't match as expected.

I really want to know, is there any plan to upgrade the version of `axios`?
Otherwise, is there any alternative way to upgrade the version of `axios` in my project only?

**Comment by jamonholmgren** [comment]
Related: #288

**Comment by EricLiuZero** [comment]
> Related: #288

Thanks for your info.

**Comment by rnike** [comment]
Is there any plan to upgrade axois to the latest version?

**Comment by jamonholmgren** [comment]
Related: #311. cc @rnike
