### ISSUE TITLE
Latest version support for Axios ?

### ISSUE THREAD

**Issue by AmalMenachery** [infinitered/apisauce#307]
We have this latest release v3.0.0, which mentions about breaking changes from Axios : https://github.com/infinitered/apisauce/releases/tag/v3.0.0 

However in the package.json https://github.com/infinitered/apisauce/blob/master/package.json we still  have 
`  "dependencies": {
    "axios": "^0.27.2"
  },`
  
  Could someone look into it ?

**Comment by moxorama** [comment]
At least there should be some TypeScript corrections

```
Type 'import("<>/node_modules/apisauce/node_modules/axios/index").AxiosRequestConfig<any>' is not assignable to type 'import("<>/node_modules/axios/index").AxiosRequestConfig<any>'
```
